/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package good.morning;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BudTest {

    Bud testBud = new Bud();

    @Test void testSaysHi() {
        assertNotNull(testBud.saysHi(), "Bud should have said Hi");
    }

    @Test void testSaysFarewell() {
        assertNotNull(testBud.saysFarewell(), "Bud should have said Farewell");
    }
}
