/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package good.morning;

import org.junit.jupiter.api.Test;

public interface BudTest {

    @Test
    String testSaysHi();

    @Test
    String testSaysFarewell();
}