/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package good.morning;

import org.junit.jupiter.api.Test;

public class SteveTest implements BudTest {

    @Test
    public String testSaysHi() {
        
        String hi = "Remember- every great day starts with a good morning!";
        return hi;
    }

    @Test
    public String testSaysFarewell() {
        
        String farewell = "Farewell!";
        return farewell;
    }
    
}
